# Generated by Django 6.1 on 2026-09-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('access_method', models.CharField(choices=[('live_api', 'Live API'), ('downloaded_snapshot', 'Downloaded snapshot'), ('reviewed_import', 'Reviewed import')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=500)),
                ('evidence_type', models.CharField(choices=[('label', 'Medicine label'), ('registration', 'Registration'), ('alert', 'Product alert'), ('product_listing', 'Product listing'), ('essential_medicine', 'Essential medicine')], max_length=30)),
                ('ingredient', models.CharField(blank=True, max_length=500)),
                ('strength', models.CharField(blank=True, max_length=150)),
                ('dosage_form', models.CharField(blank=True, max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=500)),
                ('batch', models.CharField(blank=True, max_length=255)),
                ('affected_market', models.CharField(blank=True, max_length=500)),
                ('listing_status', models.CharField(blank=True, max_length=150)),
                ('source_version', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('official_url', models.URLField(max_length=2048)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='medicines.trustedsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'record_id'), name='unique_evidence_source_record')],
            },
        ),
    ]
