# Generated by Django 6.1 on 2026-09-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dataset_url', models.URLField(max_length=2048)),
                ('license', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=500)),
                ('generic_name', models.CharField(blank=True, max_length=1000)),
                ('strength_text', models.CharField(blank=True, max_length=500)),
                ('dosage_form', models.CharField(blank=True, max_length=300)),
                ('manufacturer', models.CharField(blank=True, max_length=500)),
                ('medicine_type', models.CharField(blank=True, max_length=100)),
                ('normalized_brand_name', models.CharField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_accepted', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='medicines.catalogdataset')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('source_slug', models.CharField(blank=True, max_length=1000)),
                ('raw_row', models.JSONField()),
                ('reconciliation_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('ambiguous', 'Ambiguous'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='medicines.catalogimportbatch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='medicines.catalogproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'row_number'), name='unique_catalog_batch_row'), models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='catalog_row_number_positive')],
            },
        ),
    ]
